#ifndef QTCOMMONTOOLS_GLOBAL
#define QTCOMMONTOOLS_GLOBAL

#include <qglobal.h>

#if defined(QTCOMMONTOOLS_LIBRARY)
#  define QTCOMMONTOOLS_EXPORT Q_DECL_EXPORT
#else
#  define QTCOMMONTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOMMONTOOLS_GLOBAL

